/**
 * ECskat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Action = 'KARTEN_OFFENLEGEN' | 'KARTE_SPIELEN' | 'RAMSCH_SKAT_WEITERREICHEN' | 'REIZEN_HOEREN' | 'REIZEN_SAGEN' | 'SPIEL_ANSAGEN';

export const Action = {
    KartenOffenlegen: 'KARTEN_OFFENLEGEN' as Action,
    KarteSpielen: 'KARTE_SPIELEN' as Action,
    RamschSkatWeiterreichen: 'RAMSCH_SKAT_WEITERREICHEN' as Action,
    ReizenHoeren: 'REIZEN_HOEREN' as Action,
    ReizenSagen: 'REIZEN_SAGEN' as Action,
    SpielAnsagen: 'SPIEL_ANSAGEN' as Action
};

