/**
 * ECskat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Game = 'EICHEL' | 'GRAND' | 'GRUEN' | 'HERZ' | 'NULL' | 'NULL_HAND' | 'NULL_OUVERT' | 'NULL_OUVERT_HAND' | 'RAMSCH' | 'SCHELL';

export const Game = {
    Eichel: 'EICHEL' as Game,
    Grand: 'GRAND' as Game,
    Gruen: 'GRUEN' as Game,
    Herz: 'HERZ' as Game,
    Null: 'NULL' as Game,
    NullHand: 'NULL_HAND' as Game,
    NullOuvert: 'NULL_OUVERT' as Game,
    NullOuvertHand: 'NULL_OUVERT_HAND' as Game,
    Ramsch: 'RAMSCH' as Game,
    Schell: 'SCHELL' as Game
};

