/**
 * ECskat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameLevel = 'HAND' | 'NORMAL' | 'OUVERT' | 'SCHNEIDER_ANGESAGT' | 'SCHWARZ_ANGESAGT';

export const GameLevel = {
    Hand: 'HAND' as GameLevel,
    Normal: 'NORMAL' as GameLevel,
    Ouvert: 'OUVERT' as GameLevel,
    SchneiderAngesagt: 'SCHNEIDER_ANGESAGT' as GameLevel,
    SchwarzAngesagt: 'SCHWARZ_ANGESAGT' as GameLevel
};

