/**
 * ECskat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';
import { Game } from './game';
import { GameLevel } from './gameLevel';
import { Card } from './card';


export interface SpielResult { 
    alleinspieler?: Player;
    ausgeteilteKarten?: { [key: string]: Array<Card>; };
    eingemischt?: boolean;
    game?: Game;
    gameLevel?: GameLevel;
    gespaltenes?: boolean;
    punkteAlleinspieler?: number;
    punkteGegenspieler?: number;
    skat?: Array<Card>;
    wertungen?: { [key: string]: number; };
}

