/**
 * ECskat API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';
import { Game } from './game';
import { Card } from './card';


export interface Stich { 
    game?: Game;
    karte1?: Card;
    karte2?: Card;
    karte3?: Card;
    readOnly?: boolean;
    spieler1?: Player;
    spieler2?: Player;
    spieler3?: Player;
    winner?: Player;
}

