# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD with Maven, Docker and gcloud CLI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # https://cloud.google.com/container-registry/docs/overview
  GCR_HOSTNAME: eu.gcr.io

  PROJECT_ID: ${{ secrets.GCR_PROJECT }}

  IMAGE: ecskat
  IMAGE_TAG: latest
  # IMAGE_TAG: $GITHUB_SHA


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCR_SA_KEY }}
        project_id: ${{ secrets.GCR_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential helper for authentication
    - name: Configure Docker
      run: |-
        gcloud --quiet auth configure-docker

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Change permission
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw package

#    - name: Show docker config
#      run: more $HOME/.docker/config.json

#    - name: Login to Docker-Hub
#      run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Build with Docker
      run: |-
        docker build \
          -f src/main/docker/Dockerfile.jvm \
          --tag "$GCR_HOSTNAME/$PROJECT_ID/$IMAGE:$IMAGE_TAG" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
 
   # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "$GCR_HOSTNAME/$PROJECT_ID/$IMAGE:$IMAGE_TAG"
