name: Testdeployment

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Deploy to Cloud Run
      run: whoami
