# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Change permission
      run: chmod +x ./mvnw
    - name: Build with Maven
      run: ./mvnw package
#      run: mvn -B package -DskipTests --file pom.xml
    - name: Build with Docker
      run: docker build -f src/main/docker/Dockerfile.jvm -t quarkus/ecskat-jvm .
