# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven build before merge

on:
  workflow_dispatch:

jobs:
  build:
    name: Build before merging
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Change permission
      run: chmod +x ./mvnw

    - name: Build with Maven
      run: ./mvnw package

    - name: Build with Docker
      run: |-
        docker build \
          -f src/main/docker/Dockerfile.jvm \
          --tag "ecskat:tmp" \
          .
